### ISSUE TITLE
Launch server on Windows Help

### ISSUE THREAD

**Issue by PhantomBlade219** [SmartlyDressedGames/U3-Docs#16]
I have never coded before and I don't know how to 'Replace "New Text Document.txt" with "Tutorial.bat"'. This is step 4 of the launch server in Windows step, any help is appreciated. If you can please provide images.

**Comment by MoltonMontro** [comment]
There is no coding involved.
- Create a new text file
- Rename it to "Tutorial.bat"
![image](https://user-images.githubusercontent.com/7608445/72645513-73fb7580-3939-11ea-8254-f0cc903b560d.png)
![image](https://user-images.githubusercontent.com/7608445/72645537-7f4ea100-3939-11ea-80f3-09883a07b2fc.png)
![image](https://user-images.githubusercontent.com/7608445/72645543-82e22800-3939-11ea-9317-36d9bc0e4ab6.png)

Make sure you're actually changing the file type, and not just the name. Otherwise, you'll have Tutorial.bat.txt instead of Tutorial.bat.
![image](https://user-images.githubusercontent.com/7608445/72645680-ce94d180-3939-11ea-8b54-5de94b2b6ac4.png)

**Comment by PhantomBlade219** [comment]
you are a godsend i would not have figured this out without those pictures
