### ISSUE TITLE
Error after todays update

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/U3-Docs#220]
Not sure if anyone is getting that too, but after todays update no one can connect to server. Giving this error:
Client and server are both missing unknown asset! ID: 735bf7ba162d40babb8d43023737d131
This probably means either an invalid ID was sent by the server,
the ID got corrupted for example by plugins modifying network traffic,
or a required level asset like materials/foliage is missing.

Tried to look for such GUID through unturned bundles and server files, couldn't find. So not sure what kind of asset it is.

**Comment by SDGNelson** [comment]
The change in today's update was to convert trees and objects to use that newer asset integrity check. Trees probably don't apply in this case because maps saved with earlier versions didn't have GUIDs.

There was another report so far where an object had been uploaded to the workshop without a GUID, so each player and the server was generating a different value. If you look in the log is there a "found by legacy ID #, updating to" message? The object mentioned there might be responsible.

**Comment by baranmod** [comment]
There are lots of them, most related to foliage, some to objects. Tried to save map without objects and foliage, same thing, so not sure. Anyways, it seems to work with other maps fine. Maybe because there are no corrupted objects used there.

**Comment by Orpham-Guestino** [comment]
Its an issue for a lot of servers, it's just not working no matter what staff try.

**Comment by SDGNelson** [comment]
The .1 patch has changed it to only validate objects prior to the legacy ID fallback so it shouldn't be kicking, but fixing the underlying problem is highly recommended because otherwise players can modify those objects.
