### ISSUE TITLE
Unturned server protocol

### ISSUE THREAD

**Issue by juls0730** [SmartlyDressedGames/U3-Docs#283]
Hi SDG,

I hope this message finds you well. I've been working on building a custom Unturned server in Rust, So that I can learn a little about networking and learn a little more about how Unturned works under the hood. So far, I have successfully implemented a query server using the [Server queries documentation](https://developer.valvesoftware.com/wiki/Server_queries) provided by Valve.

Now that I'm progressing to build the actual game server, I'm facing a challenge: I can't seem to find any documentation on the protocol utilized by Unturned. But, I can't seem to find any information or leads as to how the game server works. Could you please point me in the right direction or provide some insights into the protocol?

Your assistance would be immensely appreciated. Thank you so much for your time and support.

Kind regards,
juls0730

**Comment by SDGNelson** [comment]
Thanks for your nicely written message, but sorry to say the Unturned server isn't designed to be externally reimplemented. i.e., the layout of network messages may be changed at any time without backwards compatibility. I'm not sure Unturned's network code is a particularly good point of reference if you're interested in learning about game networking because I had no prior experience when writing it. That being said, there is this repo with all of the network code: https://github.com/Unturned-Datamining/Unturned-Datamining

**Comment by juls0730** [comment]
Thanks!
