### ISSUE TITLE
Commands.dat

### ISSUE THREAD

**Issue by Christopher111111111** [SmartlyDressedGames/U3-Docs#49]
There is nothing in my Commands.dat file, so I cannot change the password, and therefore cannot join the server I created.

**Comment by SDGNelson** [comment]
By default the server does not have a password. What happened when you tried to join your server?

**Comment by MoltonMontro** [comment]
> There is nothing in my Commands.dat file, so I cannot change the password

As implied by Nelson, the Commands.dat does not automatically generate any custom settings—all desired settings need to be set and added to the file _manually_ otherwise the default is used. If you'd like to add a password, you need to add the Password command (e.g., **Password myServerPassword**) to your Commands.dat file, using a text editor such as Notepad.

If you cannot join your server, it's likely a different issue that isn't relevant to the server password. The specific error message would prove useful. Perhaps so would a backtracking of the steps you've taken or a screenshot of your server/connect screen,– my assumption is that you're trying to Connect directly via IP/Port/Password, but you're failing to connect because you're entering a password when it isn't needed.

**Comment by Christopher111111111** [comment]
Thank you MoltonMontro, I was looking at the Password setup and thought the command would be more complicated but it now works, thank you again.
