### ISSUE TITLE
Tutorial.bat doesn't launch the server

### ISSUE THREAD

**Issue by axelliranza** [SmartlyDressedGames/U3-Docs#59]
I'm not code savvy at all, and I was trying to follow your instructions but after creating the text document, naming it  tutorial.bat and pasting the LAN server info, nothing else happens. double clicking it just opens the text file again, and I don't know where this batch script is. please, explain to me what to do like i'm stupid. thank you.

**Comment by MoltonMontro** [comment]
This isn't a coding issue, but a file extension issue. You've created a text file called **Tutorial.bat.txt**. You need to have created a batch file (for example, a file called **Tutorial.bat**) instead. I can reexplain steps 3 through 9 for you.

3. Create a new text file. There are multiple ways to create files. One of the ways you can do so is by right-clicking an area of empty space inside the folder, and then selecting New > Text Document.

4. This has created a new text file called "**New Text Document.txt**". The ".txt" is the file extension, and in this case basically means it is a _text file_. We want to rename this something memorable, as we are going to turn this into a batch script that launches our server. We need to change the file extension from a text file (.txt) to a batch script file (.bat), so that we can run a script to launch the server.

   1. The easiest way to change a text file to a batch file is by manually replacing the file extension portion of the file name. If you are looking at the text document you created, and you do not see it appended with the file extension (.txt) at the very end of the file name, then you have the viewing of file extensions _disabled_. We will enable them. Refer to the image below:
![image](https://user-images.githubusercontent.com/7608445/118236468-ba90af80-b45b-11eb-9a23-8560be374e8f.png)

   2. At the top of File Explorer are several tabs. Navigate to the "View" tab. In the "Show/hide" section of options, check the "File name extensions" box. This will enable the viewing of file extensions, as appended at the end of a file name. Additionally, it means that you can change the file extension of a file by renaming the file.

   3. Rename the "**New Text Document.txt**" file. For example, you could rename it to "**Tutorial.bat**" or "**StartMyServer.bat**" The actual name of the file ("Tutorial", "StartMyServer", etc.) is not important. The actual file extension (".bat") is _very important_.

   4. You should now have a batch file. If you have your File Explorer in a layout that shows additional file details (this is optional and not necessary for anything), you may see a column for file **Type** that says "Windows Batch File".

5. We want to edit the batch file we have created. To do this, we need to open the file in a text editor. We cannot double-click the file to edit it, because it is no longer a text file. Instead, we will right-click the file, and click "Edit". This will open the batch file in your default text editor, such as Notepad. _However, you may choose to use any text editor (Notepad, WordPad, Notepad++, etc.) to open and edit the file._

6. Now that you have opened the file in a text editor, we want to add the script that will start your server.

   * Do you want to run a dedicated server, where _people outside your computer network can join_? Copy-and-paste the following text into the batch file. `start "" "%~dp0ServerHelper.bat" +InternetServer/MyServerFolderName`
      * Dedicated servers require that you open ports on your router (this is called port forwarding). This is explained in [PortForwarding.md](https://github.com/SmartlyDressedGames/U3-Docs/blob/master/PortForwarding.md).

   * Do you want to run a LAN server, where _only people on your same computer network can join_? Copy-and-paste the following text into the batch file. `start "" "%~dp0ServerHelper.bat" +LanServer/MyServerFolderName`

7. Save the file; close the file.

8. We are now going to launch your server. Double-click the batch script to launch your server. A command-line interface should appear. Because this is the first time we have ran the batch file, it is going to generate a bunch of server files. Refer to the image below for what a command-line interface looks like:
![image](https://user-images.githubusercontent.com/7608445/118238907-c336b500-b45e-11eb-8dbe-b56c5697033f.png)

9. If you look at the command-line interface, you should see many lines of text being outputted. Eventually, the server will stop outputting rows of text.

   1. When the server has stopped outputting text, it has finished loading, and it has finished generating all the necessary server files. You can safely close the server by executing (typing, and then pressing the "↵ Enter" key on your keyboard) the following command on the command-line interface: `shutdown`

   2. The batch file has created a new file directory, called "Servers". Navigate to the Servers folder. This is where all the savedata and configuration files are kept. If you wish to begin configuring your server, this is the file directory you want to be in.

**Comment by axelliranza** [comment]
Thank you so much!
